#! /bin/sh

KERNEL_VERSION=$(readlink /boot/zImage | perl -pe 's/zImage-//')
MODULES_DIR=/lib/modules/${KERNEL_VERSION}

for mod in $(ls ${MODULES_DIR}/extra/*ko 2> /dev/null) ; do 
  find ${MODULES_DIR}/kernel -name $(basename $mod) -exec rm -f {} \;
done

depmod -a ${KERNEL_VERSION}

cd /boot

ln -sf zImage-${KERNEL_VERSION} zImage
ln -sf *.dtb dtb # FIXME: careful if several DTBs

exit 0
