#! /bin/sh

KERNEL_VERSION=$(readlink /boot/zImage | perl -pe 's/zImage-//')
MODULES_DIR=/lib/modules/${KERNEL_VERSION}

for mod in $(ls ${MODULES_DIR}/extra/*ko 2> /dev/null) ; do 
  find ${MODULES_DIR}/kernel -name $(basename $mod) -exec rm -f {} \;
done

depmod -a ${KERNEL_VERSION}

# make sure we're OK even before rebooting to the new kernel
ln -sf $MODULES_DIR /lib/modules/$(uname -r)

cd /boot
ln -sf zImage-${KERNEL_VERSION} zImage
ln -sf *.dtb dtb # FIXME: careful if several DTBs

exit 0
