#########################################
## kernel conf for bookworm's 6.1 kernel

# upstream version
UPSTREAM_VERSION = 6.1.159

# debian version
DEBIAN_VERSION = 1

# repository
REPOSITORY = bookworm
